# Generated by Django 5.0.3 on 2025-04-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querylog',
            old_name='queryText',
            new_name='query',
        ),
    ]
